parameters:
#    locals_best_rest.example.class: LocalsBest\RestBundle\Example

services:
#    locals_best_rest.example:
#        class: %locals_best_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
