<?php

namespace LocalsBest\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;
use LocalsBest\UserBundle\Entity\Business;
use LocalsBest\UserBundle\Entity\User;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function queryApprovedForUser(User $user)
    {
        $qb = $this->createQueryBuilder('i');

        $qb
            ->where('i.status = :status')
            ->andWhere('i.createdBy = :user')
            ->setParameter('status', Item::STATUS_APPROVED)
            ->setParameter('user', $user)
        ;

        return $qb;
    }

    public function findAllBy(Business $business, $forApproveOnly=false)
    {
        $qb = $this->createQueryBuilder('i');

        $qb
            ->join('i.createdBy', 'u')
            ->join('u.businesses', 'b')
            ->where('b.id = :businessId')
            ->setParameter('businessId', $business->getId())
        ;

        if ($forApproveOnly === true) {
            $qb
                ->andWhere('i.status = :ableStatus')
                ->setParameter('ableStatus', Item::STATUS_PUBLISHED)
            ;
        }

        return $qb->getQuery()->getResult();
    }
    
    public function findItem($user){
        $qb = $this->createQueryBuilder('i');
        if ($user->getRole()->getLevel() > 1) {
            $qb 
               // ->where('i.type != :type')
                ->Where('i.createdBy = :user')
               // ->setParameter('type',5)
                ->setParameter('user',$user)
                ->orderBy('i.id', 'DESC');
        }
        else{
            $qb 
                ->where('i.type != :type')
                ->setParameter('type',5)
                ->orderBy('i.id', 'DESC');
        }
        return $qb->getQuery()->getResult();
    }
}
