<?php

namespace LocalsBest\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use LocalsBest\UserBundle\Entity\User;

/**
 * SkuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkuContactUsRepository extends EntityRepository
{
    public function findAllVendorRequests($user)
    {
        $qb = $this->createQueryBuilder('s');

        $qb
            ->leftJoin('s.sku', 'sk')
            ->leftJoin('sk.package', 'p')
            ->where('p.createdBy = :id')
            ->setParameter('id', $user->getId())
            ->orderBy('s.id', 'DESC');
        return $qb->getQuery()->getResult();
    }
    
    public function getUnreadCountAllVendorRequests($user)
    {
        $qb = $this->createQueryBuilder('s');

        $qb
            ->leftJoin('s.sku', 'sk')
            ->leftJoin('sk.package', 'p')
            ->where('p.createdBy = :id')
            ->andwhere('s.isread = :isread')
            ->setParameter('id', $user->getId())
            ->setParameter('isread', 0)
            ->orderBy('s.id', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
}
