parameters:
#    locals_best_shop.example.class: LocalsBest\ShopBundle\Example

services:
#    locals_best_shop.example:
#        class: %locals_best_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    shop.quantity_enough_validator:
        class: LocalsBest\ShopBundle\Validator\Constraints\QuantityEnoughValidator
        tags:
            - { name: validator.constraint_validator }