<?php

namespace LocalsBest\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlankDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlankDocumentRepository extends EntityRepository
{
    public function findByBusinessAndRole(Business $business, $role)
    {
        $qb = $this->createQueryBuilder('db');

        $qb
            ->where('db.business = :business')
            ->andWhere('db.ableRoles like :currentRole')
            ->setParameter('business', $business)
            ->setParameter('currentRole', "%".$role."%")
        ;

        $results = $qb
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }

    public function findTransactionDocsByBusinessTypeAndRole(Business $business, $role, $docTypeNames, $type)
    {
        $qb = $this->createQueryBuilder('db');

        $qb
            ->where('db.business = :business')
            ->andWhere('db.ableRoles like :currentRole')
            ->andWhere('db.title in (:names)')
            ->andWhere('db.type = :type')
            ->setParameter('business', $business)
            ->setParameter('currentRole', "%".$role."%")
            ->setParameter('names', $docTypeNames)
            ->setParameter('type', $type)
        ;

        $results = $qb
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }
}
