<?php
namespace LocalsBest\UserBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * BusinessViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessViewRepository extends EntityRepository
{
}