<?php

namespace LocalsBest\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function save(Contact $contact)
    {
        foreach ($contact->getEmails() as $email) {
            $email->setContact($contact);
            $this->getEntityManager()->persist($email);
        }
        
        foreach ($contact->getPhones() as $phone) {
            $phone->setContact($contact);
            $this->getEntityManager()->persist($phone);
        }
        
        $this->getEntityManager()->persist($contact);
        $this->getEntityManager()->flush();
    }
}
