<?php

namespace LocalsBest\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndustryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryTypeRepository extends EntityRepository
{
    public function getUsingBusiness()
    {
        $qb = $this->createQueryBuilder('it');

        $qb->orderBy('it.name', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function getActive($user)
    {
        $business = $user->getBusinesses()->first();
        $qb = $this->createQueryBuilder('i_t');

        $qb
            ->join('i_t.plan_row', 'p_r')
            ->join('p_r.plan', 'p')
            ->join('p.business', 'b')
            ->where('b.id = :businessId')
            ->andWhere('p_r.industry_group <> 6')
            ->orderBy('i_t.name', 'ASC')
            ->setParameter('businessId', $business->getId());
        return $qb;
    }

    public function getTypesArray()
    {
        $qb = $this->createQueryBuilder('t');
        $qb
            ->innerJoin('t.businesses', 'b')
            ->orderBy('t.name', 'ASC')
            ->distinct();
        return $qb->getQuery()->getArrayResult();
    }
}
