<?php

namespace LocalsBest\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteRepository extends EntityRepository
{
    public function findMyObjects($me, $myStaffs = array())
    {
        $qb = $this->createQueryBuilder('d');
        
        $qb->orWhere('d.createdBy IN (:user)')
            ->orWhere('d.createdBy = :createdBy')
            ->setParameter('createdBy', $me)
            ->setParameter('user', $myStaffs);
        
        return $qb->getQuery()->getResult();
    }

    public function findInvitesByInterval(\DateTime $start, \DateTime $end)
    {
        $qb = $this->createQueryBuilder('i');

        $qb->leftJoin('i.createdBy', 'u')
            ->where(
                $qb->expr()->andX(
                    $qb->expr()->isNotNull('i.token'),
                    $qb->expr()->between('i.created', $start->getTimestamp(), $end->getTimestamp())
                )
            )
        ;

        return $qb->getQuery()->getResult();
    }
    
    public function save(Invite $invite)
    {
        $this->getEntityManager()->persist($invite);

        $this->getEntityManager()->flush();
    }
}
