<?php

namespace LocalsBest\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
    public function getPlansByAll($state, $indType, $city)
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('p.id, pr.setupGoldPrice, pr.goldPrice, pr.setupSilverPrice, pr.silverPrice, pr.setupBronzePrice, pr.bronzePrice, b.name')
            ->join('p.rows', 'pr')
            ->join('p.businesses', 'b')
            ->join('b.address', 'a')
            ->where('pr.industryType = :typeId')
            ->andWhere('a.city = :city')
            ->andWhere('a.state = :state')
            ->setParameter('typeId', $indType)
            ->setParameter('city', $city)
            ->setParameter('state', $state->getShortName());

        return $qb->getQuery()->getResult();
    }
}
