<?php

namespace LocalsBest\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferenceRepository extends EntityRepository
{
    public function save(Preference $preferenceData)
    {
        $this->getEntityManager()->persist($preferenceData);
        $this->getEntityManager()->flush();
    }
}
