<?php

namespace LocalsBest\UserBundle\Entity;

use LocalsBest\CommonBundle\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends EntityRepository
{
}
