<?php

namespace LocalsBest\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getProductTags($id)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->select('t.name')
            ->join('t.products', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $id);

        $queryResult = $qb->getQuery()->getArrayResult();
        $result = [];

        foreach ($queryResult as $item) {
            $result[] = $item['name'];
        }

        return $result;
    }
}
