categories:
    path:     /
    defaults: { _controller: "LocalsBestShopBundle:Category:index" }

categories_show:
    path:     /{id}/show
    defaults: { _controller: "LocalsBestShopBundle:Category:show" }

categories_new:
    path:     /new
    defaults: { _controller: "LocalsBestShopBundle:Category:new" }

categories_create:
    path:     /create
    defaults: { _controller: "LocalsBestShopBundle:Category:create" }
    methods: [POST]

categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "LocalsBestShopBundle:Category:edit" }

categories_update:
    path:     /{id}/update
    defaults: { _controller: "LocalsBestShopBundle:Category:update" }
    methods: [POST|PUT]

categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "LocalsBestShopBundle:Category:delete" }
    methods: [POST|DELETE]
