<?php

namespace LocalsBest\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getForMainPage($user)
    {
        $qb = $this->createQueryBuilder('n');

        $qb
            ->leftJoin('n.forUsers', 'u_n')
            ->where('u_n.user = :user' )
            ->andWhere('u_n.read = :status')
            ->orderBy('n.created', 'DESC')
            ->setMaxResults(20)
            ->setParameter('user', $user)
            ->setParameter('status', false)
        ;

        $notifications = $qb->getQuery()->getArrayResult();

        return $notifications;
    }

    public function getCountForMainPage($user)
    {
        $qb = $this->createQueryBuilder('n');

        $qb
            ->select('COUNT(n.id)')
            ->leftJoin('n.forUsers', 'u_n')
            ->where('u_n.user = :user' )
            ->andWhere('u_n.read = :status')
            ->orderBy('n.created', 'DESC')
            ->setParameter('user', $user)
            ->setParameter('status', false)
        ;

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }
}
