<?php

namespace LocalsBest\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationRepository extends EntityRepository
{
}
